apiVersion: v1
kind: Pod
metadata:
  labels:
    app: build-pod
spec:
  containers:
    - name: buildkit
      image: moby/buildkit:v0.15.0
      commad:
        - cat
      tty: true
      volumeMounts:
        - name: home-jenkins
          mountPath: /home/jenkins/
        - name: maven-cache
          mountPath: /root/.m2
        - name: buildkit-secret
          mountPath: /root/.docker
        - name: certs
          mountPath: /certs
    - name: maven
      image: eclipse-temurin:21.0.11_10-jdk-resolute
      command:
        - cat
      tty: true
      volumeMounts:
        - name: home-jenkins
          mountPath: /home/jenkins/
        - name: maven-cache
          mountPath: /root/.m2
  volumes:
    - name: home-jenkins
      emptyDir:
    - name: maven-cache
      emptyDir: {}
    - name: buildkit-secret
      secret:
        secretName: ecr-cred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: certs
      secret:
        secretName: buildkit-client-certs
    - name: git-tmp-volume
      emptyDir: {}