apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.metadata.labels.app }}-configmap
  labels:
    app: {{ .Values.metadata.labels.app }}
data:
  RETAIL_UI_THEME: default
  RETAIL_UI_ENDPOINTS_CATALOG: http://retail-store-catalog-service
  RETAIL_UI_ENDPOINTS_CARTS: http://retail-store-carts-service
  RETAIL_UI_ENDPOINTS_CHECKOUT: http://retail-store-checkout-service
  RETAIL_UI_ENDPOINTS_ORDERS: http://retail-store-orders-service
  RETAIL_UI_SEARCH_ENABLED: "false"
  RETAIL_UI_CHAT_BEDROCK_REGION: ap-south-1