apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.labels.app }}-service
  labels:
    app: {{ .Values.metadata.labels.app }}
spec:
  selector:
    app: {{ .Values.metadata.labels.app }}
  ports:
    - port: {{ .Values.containers.ports.containerPort }}
      targetPort: {{ .Values.containers.ports.containerPort }}
      nodePort: 30002
  type: NodePort